name: API tests

on: [ pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend repository
        uses: actions/checkout@v3
        with:
          repository: bondarenkokate73/simbirsoft_sdet_project
          path: backend
      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
      - name: Run docker-compose
        run: |
          cd backend
          docker compose up -d --build
      - name: Wait for Backend
        run: |
          sleep 30

      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system -r requirements.txt

      - name: Run ui tests
        run: |
          pytest -k "TestEntity" -v -n 3 --alluredir=api-allure-results
        continue-on-error: true

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: api-allure-results
          path: api-allure-results
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: run-api-tests
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '21.0.2'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz && sudo tar -zxvf allure-2.29.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Download allure results
        uses: actions/download-artifact@v4
      - run: |
          mkdir -p _site/api
          allure generate -c api-allure-results -o _site/api
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: _site/api
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download allure results
        uses: actions/download-artifact@v4
      - name: Upload allure report
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - run: echo "https://sfz111.github.io/SimbirsoftTask/api/"
