name: API Tests

on: [pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backend repository
        uses: actions/checkout@v3
        with:
          repository: bondarenkokate73/simbirsoft_sdet_project
          path: backend

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: |
          cd backend
          docker compose up -d --build

      - name: Wait for Backend
        run: |
          timeout 120 bash -c '
            until [ "$(docker inspect -f "{{.State.Status}}" service)" = "running" ]; do
              echo "Waiting for container to start...";
              sleep 5;
            done
          '

      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Run api tests
        run: |
          pytest -k "TestEntity" -v -n 3 --alluredir=allure-results-api
        continue-on-error: true

      - name: Store API allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: allure-results-api
          retention-days: 90

  generate-report:
    runs-on: ubuntu-latest
    needs: [run-api-tests]
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure

      - name: Download API results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: allure-results-api

      - name: Generate report
        run: |
          mkdir -p report-api/api
          allure generate allure-results-api -o report-api/api --clean
          
          find report-api/api -type f \( -name '*.html' -o -name '*.js' \) -exec sed -i 's|/static/|./static/|g' {} \;
          echo '<base href="/SimbirsoftTask/api/">' >> report-api/api/index.html

      - name: Add .nojekyll file
        run: |
          touch report-api/.nojekyll
          echo "Disabled Jekyll processing" > report-api/.nojekyll

      - name: Verify report structure
        run: |
          echo "Generated files:"
          ls -laR report-api/api
          [ -f "report-api/api/index.html" ] || { echo "Error: index.html not found"; exit 1; }

      - name: Upload API report only
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: report-api
          retention-days: 90
