name: Deploy Reports

on:
  workflow_run:
    workflows: [ "UI Tests", "API Tests" ]
    types: [ completed ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download UI report
        uses: actions/download-artifact@v4
        with:
          name: ui-report
          path: _site/ui

      - name: Download API report
        uses: actions/download-artifact@v4
        with:
          name: api-report
          path: _site/api

      - name: Create index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Test Reports</title>
            <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
          </head>
          <body>
            <h1>Available Reports:</h1>
            <ul>
              <li><a href="/ui/">UI Tests</a></li>
              <li><a href="/api/">API Tests</a></li>
            </ul>
          </body>
          </html>' > _site/index.html

      - name: Add .nojekyll
        run: touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Print report URL
        run: |
          echo "API Report: https://sfz111.github.io/SimbirsoftTask/api/"
          echo "UI Report: https://sfz111.github.io/SimbirsoftTask/ui/"
