name: Independent Tests with Reports

on: [ pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:


  run-api-tests:
    runs-on: ubuntu-latest
    steps:


  generate-reports:
    runs-on: ubuntu-latest
    needs:
      - run-ui-tests
      - run-api-tests
    if: always()
    steps:


      - name: Generate reports
        run: |
          mkdir -p combined-report
          
          
          if [ -d "allure-results/ui" ]; then
            echo "Generating UI report..."
            allure generate allure-results/ui -o combined-report/ui --clean

            if [ -d "combined-report/ui" ]; then
              find combined-report/ui -type f \( -name '*.html' -o -name '*.js' \) -exec sed -i 's|/static/|./static/|g' {} \;
              echo '<base href="/SimbirsoftTask/ui/">' >> combined-report/ui/index.html
              echo "UI report generated successfully"
            else
              echo "Error: UI report was not generated"
          
              mkdir -p combined-report/ui
              echo "<h1>UI Test Report</h1><p>No test results available</p>" > combined-report/ui/index.html
            fi
          else
            echo "No UI test results found"
            mkdir -p combined-report/ui
            echo "<h1>UI Test Report</h1><p>No test results found</p>" > combined-report/ui/index.html
          fi
          
          if [ -d "allure-results/api" ]; then
            echo "Generating API report..."
            allure generate allure-results/api -o combined-report/api --clean
            find combined-report/api -type f \( -name '*.html' -o -name '*.js' \) -exec sed -i 's|/static/|./static/|g' {} \;
            echo '<base href="/SimbirsoftTask/api/">' >> combined-report/api/index.html
          else
            echo "No API test results found"
          fi
          
          touch combined-report/.nojekyll
          echo "Disabled Jekyll processing" > combined-report/.nojekyll

      - name: Verify report structure
        run: |
          echo "Checking report structure..."
          ls -laR combined-report
          [ -f "combined-report/ui/index.html" ] || { echo "Error: UI index.html not found"; exit 1; }
          [ -f "combined-report/api/index.html" ] || { echo "Error: API index.html not found"; exit 1; }

      - name: Print Report URLs
        run: |
          echo "UI Report: https://sfz111.github.io/SimbirsoftTask/ui/"
          echo "API Report: https://sfz111.github.io/SimbirsoftTask/api/"


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./combined-report
          keep_files: true

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: combined-test-report
          path: combined-report
          retention-days: 90