name: Combined Tests and Reports

on: [pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout Backend repository
        uses: actions/checkout@v3
        with:
          repository: bondarenkokate73/simbirsoft_sdet_project
          path: backend

      - name: Set up Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Run docker-compose
        run: |
          cd backend
          docker compose up -d --build

      - name: Wait for Backend
        run: |
          timeout 120 bash -c '
            until [ "$(docker inspect -f "{{.State.Status}}" service)" = "running" ]; do
              echo "Waiting for container to start...";
              sleep 5;
            done
          '

      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system -r requirements.txt

      - name: Run api tests
        run: |
          pytest -k "TestEntity" -v -n 3 --alluredir=allure-results/api
        continue-on-error: true

      - name: Store API allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-api
          path: allure-results/api
          retention-days: 1

  run-ui-tests:
    runs-on: ubuntu-latest
    name: Run UI Tests
    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system -r requirements.txt

      - name: Run ui tests
        run: |
          pytest tests/ui -v -n 3 --headless --alluredir=allure-results/ui
        continue-on-error: true

      - name: Store UI allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results/ui
          retention-days: 90

  generate-reports:
    runs-on: ubuntu-latest
    needs: [run-api-tests, run-ui-tests]
    name: Generate Reports
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure

      - name: Download API results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-api
          path: allure-results/api

      - name: Download UI results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results/ui

      - name: Generate reports
        run: |
          mkdir -p _site
          
          # Generate API report
          if [ -d "allure-results/api" ]; then
            allure generate allure-results/api -o _site/api --clean
            echo '<base href="/SimbirsoftTask/api/">' >> _site/api/index.html
          fi
          
          # Generate UI report
          if [ -d "allure-results/ui" ]; then
            allure generate allure-results/ui -o _site/ui --clean
            echo '<base href="/SimbirsoftTask/ui/">' >> _site/ui/index.html
          fi
          
          # Create .nojekyll file
          touch _site/.nojekyll
          echo "Disabled Jekyll processing" > _site/.nojekyll

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: _site
          retention-days: 1

  publish-reports:
    runs-on: ubuntu-latest
    needs: generate-reports
    name: Publish Reports
    steps:
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: test-reports
          path: _site

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Print report URLs
        run: |
          echo "API Report: https://sfz111.github.io/SimbirsoftTask/api/"
          echo "UI Report: https://sfz111.github.io/SimbirsoftTask/ui/"
