name: UI Tests

on: [ pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    name: Run UI Tests

    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies with uv
        run: |
          uv pip install --system -r requirements.txt

      - name: Run ui tests
        run: |
          pytest tests/ui -v -n 3 --headless --alluredir=allure-results-ui
        continue-on-error: true

      - name: Store UI allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results-ui
          retention-days: 90

  generate-report:
    runs-on: ubuntu-latest
    needs: [ run-ui-tests ]
    name: Generate Report

    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure

      - name: Download UI results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results-ui

      - name: Generate report
        run: |
          mkdir -p _site/ui
          allure generate allure-results-ui -o _site/ui --clean
          # Фикс путей для GitHub Pages
          find _site/ui -type f -name "*.html" -exec sed -i 's|/static/|./static/|g' {} \;
          find _site/ui -type f -name "*.js" -exec sed -i 's|/static/|./static/|g' {} \;

      - name: Add .nojekyll file
        run: |
          touch _site/.nojekyll
          echo "Disabled Jekyll processing" > _site/.nojekyll

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: _site
          retention-days: 90

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish Report

    steps:
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: _site

      - name: Verify report structure
        run: |
          ls -laR _site
          [ -f "_site/ui/index.html" ] || exit 1

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Print report URL
        run: |
          echo "UI Report: https://sfz111.github.io/SimbirsoftTask/ui/"
          echo "Direct link: https://sfz111.github.io/SimbirsoftTask/ui/index.html" # Для случаев, когда основной URL не работает
