name: UI Tests

on: [ pull_request ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system -r requirements.txt

      - name: Run ui tests
        run: |
          pytest tests/ui -v -n 3 --headless --alluredir=allure-results-ui
        continue-on-error: true

      - name: Store UI allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results-ui
          retention-days: 90

  generate-report:
    runs-on: ubuntu-latest
    needs: [ run-ui-tests ]
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '21.0.2'

      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure

      - name: Download UI results
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ui
          path: allure-results-ui

      - name: Generate report
        run: |
          mkdir -p report-ui/ui
          allure generate allure-results-ui -o report-ui/ui --clean
          
          find report-ui/ui -type f \( -name '*.html' -o -name '*.js' \) -exec sed -i 's|/static/|./static/|g' {} \;
          echo '<base href="/SimbirsoftTask/ui/">' >> report-ui/ui/index.html

      - name: Upload UI report only
        uses: actions/upload-artifact@v4
        with:
          name: ui-report
          path: report-ui
          retention-days: 90

