name: UI Tests

on: [pull_request]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies with uv
      run: |
        uv pip install --system -r requirements.txt

    - name: Run ui tests
      run: |
        pytest tests/ui -v -n 3 --headless --alluredir=allure-results
